### ISSUE TITLE
Vanishing HTML

### ISSUE THREAD

**Issue by ericelliott** [jsbin/jsbin#2668]
Sometimes JSBin does not load the HTML I have saved with a bin. This is extremely problematic.
## Reproduce

The problem is **intermittent**. Refreshing or closing/reopening the link may or may not fix it.

[Link to bin](https://jsbin.com/nimenu/1/edit?html,js,output)

Console output:

```
jsbin-3.35.5.min.js:17 Dave is ready.
edit:1 Mixed Content: The page at 'https://jsbin.com/nimenu/edit?html,js,output' was loaded over HTTPS, but requested an insecure image 'http://i0.wp.com/blank'. This request has been blocked; the content must be served over HTTPS.
jsbin-3.35.5.min.js:18 Processor is not ready yet - trying again
runner-3.35.5.min.js:1 d[ o_0 ]b
```

Browser:

```
Google Chrome   47.0.2526.106 (Official Build) (64-bit)
Revision    19b9e1a5713f4b9ae324bd59bbe16ca6eb91d0e0-refs/branch-heads/2526@{#532}
OS  Mac OS X
```
## Actual Output

The entire contents of the HTML tab seems to be replaced with the React scripts...

<img width="1281" alt="screen shot 2016-01-07 at 6 04 08 pm" src="https://cloud.githubusercontent.com/assets/364727/12187501/b3eca96e-b569-11e5-8347-5870bb9d46ac.png">

Clicking the "run" button doesn't seem to do anything at this point.
## Expected Output

<img width="1919" alt="screen shot 2016-01-07 at 6 08 10 pm" src="https://cloud.githubusercontent.com/assets/364727/12187509/bf439840-b569-11e5-8b11-9542c784dc62.png">

**Comment by remy** [comment]
I'm not suggesting this is the solution, but does it behave consistently over http out of interest?

**Comment by ericelliott** [comment]
It seems to behave the same over http/https...

**Comment by remy** [comment]
Hmm, I think I might know why. The selection of the React JSX language requires a script tag to be inserted, but it's possible that there's some race to get the content in...

I don't have any time today to look, but I know where to start and think it's related to the new way the bins are loaded (from about 4 months ago). I'm certain I have time this coming week in the evenings to look.

**Comment by ericelliott** [comment]
> The selection of the React JSX language requires a script tag to be inserted, but it's possible that there's some race to get the content in...

That is exactly the theory that jumped into my head. I really appreciate the time. I'm experimenting with using JSBin in my new blog posts. See ["Master the JavaScript Interview: What is a Closure?"](https://medium.com/javascript-scene/master-the-javascript-interview-what-is-a-closure-b2f0d2152b36#.7y59iaduy) for example. The blog gets significant traffic, and I'm happy to send new users your way.

Thanks for all your hard work! =)

**Comment by jayphelps** [comment]
Still seeing this btw. Any progress @remy ?

**Comment by remy** [comment]
None. It's near impossible for me to fix without being able to replicate.
At a guess a stream is pushing blank HTML into your session, but that feels
extremely unlikely.

**Comment by jayphelps** [comment]
@remy oh I didn't realize you couldn't reproduce, sorry bout that.

For me, it happens every single time I load up http://jsbin.com/dutoga/edit?js,output for the first time in the session. I have modify the JavaScript in some way for it to work.

Here's a video of me reproducing, but happy to do a Screenhero session with you to let you debug on my machine directly:

![ezgif-3347123420](https://cloud.githubusercontent.com/assets/762949/14553439/7bd129f4-029b-11e6-8779-2a1ebe0c600f.gif)

**Comment by ericelliott** [comment]
In case it's helpful, I don't see the "Processor is not ready yet" message when it works:

```
Dave is ready.
jsbin-3.35.12.min.js:2 To edit settings, type this string into the console: o7p9prc61ea8
runner-3.35.12.min.js:1 d[ o_0 ]b
```

**Comment by pstephenwille** [comment]
Cloned a few bins from Egghead.io and none of them will run.  They all choke on the same error:
`Processor is not ready yet - trying again
` d[ o_0 ]b

**Comment by remy** [comment]
Can you share a URL?

**Comment by mika76** [comment]
This has been happening to me all day.

**Comment by mickeypuri** [comment]
Hi I'm also seeing this intermittent issue. The complaint is over a request to http://io.wp.com/blank

however i only see the issue on chrome, it works fine in firefox and ie

**Comment by ericelliott** [comment]
I'm not sure if this has been fixed or not, because I stopped using & recommending JSBin because of this issue. It made it unusable for sharing bins. People complained that the bin didn't work, even though it worked on my machine when I made the bin.

**Comment by remy** [comment]
@ericelliott understandable. And a shame on my part - the whole code base needed a refactor to get ahead of these bugs. It's unlikely you'll be inclined to, but I'm confident that you'll see this issue solved in jsbin v5 (to preview it, there's directions in the browsers' native console).

**Comment by ericelliott** [comment]
I'll definitely give it another try. Thanks for the hard work you put into it. =)

**Comment by timtwomey** [comment]
Ad Blocker appears to be the issue for me. 3 js files weren't loading (e.g. processor.js). Had to add jsbin to list of ignored sites.

**Comment by hkjpotato** [comment]
is there any update about this issue? I still see the same, unforturnately

**Comment by dd301** [comment]
Pausing adblocker on jsbin doesn't work either. I tried to import a script element using HTML but it doesn't work.
